### ISSUE TITLE
[Discussion] Covered concepts and components

### ISSUE THREAD

**Issue by marktani** [graphql-boilerplates/node-graphql-server#1]
* [ ] all kinds of schema transformation/stitching/hiding
* [ ] file proxy
* [ ] authentication layer
* [ ] middleware concepts

**Comment by kbrandwijk** [comment]
- Regarding schema transformation, I would wait for the next graphql-tools release, because transformSchema falls short in many ways, and this will be built in to graphql-tools anyways.

- Regarding authentication. I would suggest using GraphQL middleware for that. Also, use a standard Express middleware for dealing with JWT tokens, instead of doing everything manually.

- Regarding file proxy. Do you need your own file proxy implementation? Or should this rather be one of the Gateway examples instead of being part of the boilerplate?

- What other middleware concepts are you thinking of?
